syntax match Comment "--.*$"
syntax match Delimiter ","
syntax match Function "\["
syntax match Function "\]"
syntax match Function "!"
syntax match Function "\v\.\w+"
syntax match Label "\v\@(\w|-)*"
syntax match TypeDef "\v'(\w|-)+"
